
[window]
title = "Terminal"
dynamic_title = false
opacity = 0.90

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[cursor]
style = { shape = "Underline", blinking="On"}
unfocused_hollow = false

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[general]
import = [
"/home/mrettig/.config/alacritty/catppuccin-mocha.toml"
]
